models/Profile.py
from main import db

class Profile(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	pet_name = db.Column(db.String(30))
	pet_breed = db.Column(db.String(30))
	pet_dob = db.Column(db.String(30))
	pet_sex = db.Column(db.String(30))

models/User.py
from main import db
from flask_login import UserMixin
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import InputRequired, Email, Length

def get_user(user_id):
    user=User.query.filter_by(id=user_id).first()
    return user

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(80))

class LoginForm(FlaskForm):
    username = StringField('username', validators=[InputRequired(), Length(min=4, max=15)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8, max=80)])
    remember = BooleanField('remember me')

class RegisterForm(FlaskForm):
    email = StringField('email', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50),])
    username = StringField('username', validators=[InputRequired(), Length(min=4, max=15)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8, max=80)])

models/Vaccine.py
from main import db

class Vaccine(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	vaccine = db.Column(db.String(30))
	date = db.Column(db.String(30))
	next_due = db.Column(db.String(30))

controllers/__init__.py
from controllers.profile_controller import profile , index , process
from controllers.vaccine_controller import vaccine , vaccination , vprocess
from controllers.auth_controller import login , signup , logout

registerable_controllers = [
    profile,
    index,
    process,
    vaccine,
    vaccination,
    vprocess,
    login,
    signup,
    logout
]

controllers/auth_controller.py
from models.User import User , LoginForm , RegisterForm
from main import db
from flask import Blueprint, request, jsonify, render_template, abort, redirect, url_for
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash


login = Blueprint('login',__name__, url_prefix="/")
signup = Blueprint('signup',__name__,url_prefix="/")
logout = Blueprint('logout',__name__, url_prefix="/")


@login.route('/login', methods=['GET', 'POST'])
def login_route():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                return redirect(url_for('index.index_load'))

        return render_template('login.html', form=form)


    return render_template('login.html', form=form)

@signup.route('/signup', methods=['GET', 'POST'])
def signup_route():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        username = request.form.get('username')
        email = request.form.get('email')
        email_1 = User.query.filter_by(email=email).first()
        user = User.query.filter_by(username=username).first()
        if user:
            return abort(400, description="user already exists")
        elif email_1:
            return abort(400, description="email already exists") 


        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('login.login_route'))
        

    return render_template('signup.html', form=form)


@logout.route('/logout')
@login_required
def logout_route():
    logout_user()
    return redirect(url_for('login.login_route'))

controllers/profile_controller.py
from models.Profile import Profile
from main import db
from flask import Blueprint, request, jsonify, render_template, abort, redirect, url_for
from flask_login import login_required, current_user


profile = Blueprint('profile',__name__, url_prefix="/")
process = Blueprint('process',__name__,url_prefix="/profile")
index = Blueprint('index',__name__, url_prefix="/")

@index.route('/')
@login_required
def index_load():
    result = Profile.query.all()
    return render_template('index.html', result=result)

@profile.route('/profile')
@login_required
def profile_add():
    return render_template('profile.html')

@process.route('/process',methods = ['POST'])
@login_required
def process_route():
	pet_name = request.form['pet_name']
	pet_breed = request.form['pet_breed']
	pet_dob = request.form['pet_dob']
	pet_sex = request.form['pet_sex']
	diarydata =Profile(pet_name=pet_name,pet_breed=pet_breed, pet_dob=pet_dob,pet_sex=pet_sex)
	db.session.add(diarydata)
	db.session.commit()
	return redirect(url_for('index.index_load'))


	

controllers/vaccine_controller.py
from models.Vaccine import Vaccine
from main import db
from flask import Blueprint, request, jsonify, render_template, abort, redirect, url_for
from flask_login import login_required, current_user


vaccination = Blueprint('vaccination',__name__, url_prefix="/")
vprocess = Blueprint('vprocess',__name__,url_prefix="/")
vaccine = Blueprint('vaccine',__name__, url_prefix="/")


@vaccination.route('/vaccination')
@login_required
def vaccination_route():
    result = Vaccine.query.all()
    return render_template('vaccination.html', result=result)

@vaccine.route('/vaccination/vaccine')
@login_required
def vaccine_route():
   return render_template('vaccine.html')


@vprocess.route('/vaccination/vaccine/vprocess',methods = ['POST'])
@login_required
def vprocess_route():
	vaccine = request.form['vaccine']
	date = request.form['date']
	next_due = request.form['next_due']
	diarydata =Vaccine(vaccine=vaccine,date=date,next_due=next_due)
	db.session.add(diarydata)
	db.session.commit()
	return redirect(url_for('vaccination.vaccination_route'))

main.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager


app = Flask(__name__)
# app.config['SQLALCHEMY_DATABASE_URI'] ='postgresql+psycopg2://postgres:1962@localhost/diary'
app.config['SQLALCHEMY_DATABASE_URI'] ='postgres://cnotxobzwgzncz:42c1670ab07b580fdbac2ebde20f5fd35650dde3397ca355e0a6300cd5e0e2de@ec2-54-145-249-177.compute-1.amazonaws.com:5432/dejnqbve7qnjdq'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']= False
app.config['SECRET_KEY'] = 'Thisissupposedtobesecret!'
db = SQLAlchemy(app)
bootstrap = Bootstrap(app)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login.login_route'    

from controllers import registerable_controllers

for controller in registerable_controllers:
    app.register_blueprint(controller)

from models.User import get_user

@login_manager.user_loader
def load_user(user_id):
    return get_user(user_id)

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Welcome to Pet Diary</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" >
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7XRV3Q0S9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7XRV3Q0S9');
</script>

  </head>

  <body>
    <nav style="margin-top:25px;margin-left:150px">
      <a class="btn btn-primary" href="{{ url_for('vaccination.vaccination_route') }}">Vaccination record</a>
      <a class="btn btn-primary" href="{{ url_for('logout.logout_route') }}">Log Out</a>
    </nav>
    <br>

    <div class="container theme-showcase" role="main">

      <div style="color:#fff; background-color:rgb(18, 49, 117)", class="jumbotron">
        <h1>Pet details</h1>  
      </div>

      <nav style="margin-top:25px;margin-bottom:45px">
        <a class="btn btn-primary" href="{{ url_for('profile.profile_add') }}">Add pet details</a>
      </nav>  
      <!--for loop starts-->
      {% for r in result %}

      <table style="width:100%" border="1">
        <tr>
          <th>Pet Name:</th>
          <td>{{r.pet_name }}</td>
        </tr>
        <tr>
          <th>Pet breed</th>
          <td>{{r.pet_breed }}</td>
        </tr>
        <tr>
          <th>Pet DOB</th>
          <td>{{r.pet_dob }}</td>
        </tr>
        <tr>
          <th>Pet sex</th>
          <td>{{r.pet_sex }}</td>
        </tr>
      </table>
      <br>
      <br>


      {% endfor %}

      <!-- for loop ends here..-->

    </div> <!-- /container -->

  </body>
</html>

templates/login.html
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7XRV3Q0S9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7XRV3Q0S9');
</script>
</head>


{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='signin.css')}}">
{% endblock %}

{% block content %}
<nav style="margin-top:25px;margin-left:150px">
  <a class="btn btn-primary" href="{{ url_for('signup.signup_route') }}">Signup</a>
</nav>

  <div class="container">

    <form class="form-signin" method="POST" action="/login">
      <h2 class="form-signin-heading">Please sign in</h2>
      {{ form.hidden_tag() }}
      {{ wtf.form_field(form.username) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.remember) }}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

  </div> <!-- /container -->
{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add your pet details</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" >

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7XRV3Q0S9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7XRV3Q0S9');
</script>


  </head>

  <body>
    <br>
    <br>

    <div class="container">

      <form action="profile/process" method="post">
        <div class="form-group">
          <label for="pet_name">Pet Name</label>
          <input type="text" id="pet_name" name="pet_name" class="form-control" placeholder="Add pet name here.." required autofocus>
        </div>
        <div class="form-group">
          <label for="pet_breed" >Pet Breed</label>
            <textarea class="form-control" rows="5" id="pet_breed" name="pet_breed" "placeholder=" Add your pet breed here.." required></textarea>
        </div>
        <div class="form-group">
          <label for="pet_breed" >Pet date of birth</label>
            <textarea class="form-control" rows="5" id="pet_dob" name="pet_dob" "placeholder=" Add your pet DOB here.." required></textarea>
        </div>
        <div class="form-group">
          <label for="pet_breed" >Pet sex</label>
            <textarea class="form-control" rows="5" id="pet_sex" name="pet_sex" "placeholder=" Add your pet sex here.." required></textarea>
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit  Your pet details</button>
      </form>

    </div> <!-- /container -->

  </body>
</html>

templates/signup.html
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7XRV3Q0S9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7XRV3Q0S9');
</script>
</head>


{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Sign Up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='signin.css')}}">
{% endblock %}

{% block content %}

<nav style="margin-top:25px;margin-left:150px">
  <a class="btn btn-primary" href="{{ url_for('login.login_route') }}">login</a>
</nav>
<div class="container">

  <form class="form-signin" method="POST" action="/signup">
    <h2 class="form-signin-heading">Sign Up</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.password) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
  </form>

</div> <!-- /container -->
{% endblock %}

templates/vaccination.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Vaccination record</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" >

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7XRV3Q0S9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7XRV3Q0S9');
</script>

  </head>

  <body>
    <nav style="margin-top:25px;margin-left:150px">
      <a class="btn btn-primary" href="{{ url_for('index.index_load') }}">Pet Details</a>
      
      

    </nav>
    <br>

    <div class="container theme-showcase" role="main">

      <div style="color:#fff; background-color:rgb(18, 49, 117)", class="jumbotron">
        <h1>Vaccination record</h1>
      </div>
      <nav style="margin-top:25px;margin-bottom:45px">
        <a class="btn btn-primary" href="{{ url_for('vaccine.vaccine_route') }}">Add vaccination details</a>
      </nav>
      <!--for loop starts-->
      {% for r in result %}


      <table style="width:100%" border="1">
        <tr>
          <th>Vaccine</th>
          <td>{{r.vaccine }}</td>
        </tr>
        <tr>
          <th>Vaccination date</th>
          <td>{{r.date }}</td>
        </tr>
        <tr>
          <th>Next due date</th>
          <td>{{r.next_due}}</td>
        </tr>
      </table>
      <br>
      <br>

      {% endfor %}

      <!-- for loop ends here..-->

    </div> <!-- /container -->

  </body>
</html>

templates/vaccine.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add your vaccination records</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" >

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7XRV3Q0S9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7XRV3Q0S9');
</script>


  </head>

  <body>
    <br>
    <br>

    <div class="container">

      <form action="/vaccination/vaccine/vprocess" method="post">
        <div class="form-group">
          <label for="vaccine">Vaccine</Vaccine>
          <input type="text" id="inputVaccine" name="vaccine" class="form-control" placeholder="Add vaccine here.." required autofocus>
        </div>
        <div class="form-group">
          <label for="date" >Date</label>
          <input type="text" id="inputdate" name="date" class="form-control" placeholder="Add vaccination date here.." required autofocus>
        </div>
        <div class="form-group">
          <label for="next_due" >next due date</label>
          <input type="text" id="inputnextdue" name="next_due" class="form-control" placeholder="Add next due date here.." required autofocus>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit  Your Vaccine</button>
      </form>

    </div> <!-- /container -->

  </body>
</html>